# Generated by Django 3.2 on 2021-04-30 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20190907_1432'),
        ('movies', '0002_auto_20210430_2309'),
    ]

    operations = [
    ]
